#WPA2 Personal hotspot configuration
# SSID = KALIWPA2HOTSPOT
# WPA KEY = password123

interface=wlan0
# Note change wlan0 to the Wi-Fi interface you wish to use.

driver=nl80211
ieee80211n=1
wmm_enabled=1
# wmm_enabled is highly recommended for best performance

ssid=KALIWPA2HOTSPOT
# The SSID can be changed to suit your needs

hw_mode=g
channel=6
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=password123
# change this passphrase to something only you know (a secret)!

wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
