# OPEN WIFI NETWORK
# SSID = KALIOPENHOTSPOT
interface=wlan0
driver=nl80211
ssid=KALIOPENHOTSPOT
hw_mode=g
channel=6

# Enable modern speeds (Works perfectly with open networks)
ieee80211n=1
wmm_enabled=1

# Accept all client MAC addresses without filtering
macaddr_acl=0

# Open System Authentication (0 = No Authentication/Open)
auth_algs=1

# Disable WPA/RSN security completely
wpa=0
